import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'pt' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  pt: {
    // Header
    'nav.home': 'Home',
    'nav.about': 'Sobre Nós',
    'nav.services': 'Serviços',
    'nav.benefits': 'Vantagens',
    'nav.blog': 'Blog',
    'nav.contact': 'Contato',
    'nav.contactUs': 'Fale Conosco',
    'nav.personalCredit': 'Crédito Pessoal',
    'nav.specialSavings': 'Poupança Especial',
    
    // Common
    'common.learnMore': 'Saiba Mais',
    'common.getStarted': 'Começar Agora',
    'common.contactSpecialist': 'Falar com Especialista',
    'common.simulateNow': 'Simular Agora',
    'common.sendMessage': 'Enviar Mensagem',
    'common.sending': 'Enviando...',
    'common.allRightsReserved': 'Todos os direitos reservados',
    'common.quickLinks': 'Links Rápidos',
    'common.contact': 'Contato',
    
    // Home page
    'home.hero.welcome': 'BEM-VINDO(A) À',
    'home.hero.company': 'MBG FINANCEIRA',
    'home.hero.subtitle': 'Crédito Simples e Poupança Segura.',
    'home.hero.description': 'Soluções financeiras sem burocracia para transformar seus planos em realidade.',
    'home.hero.cta': 'Simule seu Crédito Agora',
    'home.services.title': 'Soluções Financeiras ao seu Alcance',
    'home.services.subtitle': 'Oferecemos produtos financeiros pensados para facilitar sua vida e realizar seus sonhos.',
    'home.services.credit.title': 'Crédito Facilitado',
    'home.services.credit.description': 'Acesse o crédito que você precisa com pagamentos semanais flexíveis e condições justas. Processo rápido e sem complicação.',
    'home.services.savings.title': 'Poupança Especial',
    'home.services.savings.description': 'Multiplique seus lucros. Faça seu dinheiro render com total segurança e garantia. Rentabilidade superior à poupança tradicional.',
    'home.features.title': 'Vantagens que só a MBG Oferece',
    'home.features.subtitle': 'Descubra por que somos a escolha certa para suas necessidades financeiras.',
    'home.testimonials.title': 'A Confiança dos Nossos Clientes',
    'home.testimonials.subtitle': 'Veja o que nossos clientes dizem sobre os nossos serviços e resultados.',
    'home.cta.title': 'Pronto para começar?',
    'home.cta.subtitle': 'Fale com um de nossos especialistas e descubra a melhor solução para você. Estamos aqui para transformar seus planos em realidade.',
    'home.cta.button': 'Fale Conosco pelo WhatsApp',

    // About page
    'about.banner.title': 'Nossa História, Seu Futuro Financeiro',
    'about.banner.subtitle': 'Conheça a MBG Financeira e nossa missão de transformar vidas através de soluções financeiras acessíveis',
    'about.mission.title': 'MBG: Nascemos para Descomplicar',
    'about.mission.description': 'A MBG Financeira nasceu com o propósito de democratizar o acesso aos serviços financeiros no Brasil. Acreditamos que todos merecem oportunidades justas e transparentes para realizar seus sonhos e superar desafios financeiros. Nossa missão é oferecer crédito acessível e poupança segura, sempre com a confiança e o respeito que nossos clientes merecem.',
    'about.values.trust': 'Confiança',
    'about.values.trust.desc': 'Transparência total em todas as nossas operações e relacionamentos com clientes.',
    'about.values.accessibility': 'Acessibilidade',
    'about.values.accessibility.desc': 'Soluções financeiras pensadas para atender todos os perfis de brasileiros.',
    'about.values.simplicity': 'Simplicidade',
    'about.values.simplicity.desc': 'Processos descomplicados e atendimento humanizado para facilitar sua vida.',
    'about.values.commitment': 'Compromisso',
    'about.values.commitment.desc': 'Dedicação genuína em ajudar nossos clientes a alcançarem seus objetivos.',
    'about.location.title': 'Nossa Casa é sua Casa',
    'about.location.subtitle': 'Visite-nos em nossa sede e conheça pessoalmente nossa equipe de especialistas financeiros.',
    'about.location.address': 'Endereço',
    'about.location.hours': 'Horário de Funcionamento:',
    'about.location.weekdays': 'Segunda a Sexta: 8h às 18h',
    'about.location.saturday': 'Sábado: 8h às 12h',

    // Credit Personal page
    'credit.banner.title': 'Crédito Pessoal Rápido e sem Burocracia',
    'credit.banner.subtitle': 'O impulso que você precisa, com as condições que você merece',
    'credit.howItWorks.title': 'Como Funciona',
    'credit.howItWorks.subtitle': 'Processo simples e transparente em apenas 3 etapas',
    'credit.howItWorks.step1': '1. Simulação Online',
    'credit.howItWorks.step1.desc': 'Faça sua simulação rapidamente e descubra as melhores condições para seu perfil.',
    'credit.howItWorks.step2': '2. Análise Rápida',
    'credit.howItWorks.step2.desc': 'Nossa equipe analisa seu perfil em até 24 horas úteis com total segurança.',
    'credit.howItWorks.step3': '3. Dinheiro na Conta',
    'credit.howItWorks.step3.desc': 'Aprovado? O valor é depositado diretamente em sua conta de forma rápida e segura.',
    'credit.conditions.title': 'Nossas Condições',
    'credit.conditions.subtitle': 'Transparência total e condições justas para você',
    'credit.conditions.fair': 'Condições Justas',
    'credit.conditions.fair.desc': 'Valores Transparentes',
    'credit.conditions.flexible': 'Pagamento Flexível',
    'credit.conditions.flexible.desc': 'Pagamentos Semanais',
    'credit.conditions.amounts': 'Valores',
    'credit.conditions.amounts.range': 'R$ 1.000 até R$ 5.000',
    'credit.requirements.title': 'Pré-Requisitos',
    'credit.requirements.subtitle': 'Documentação necessária para solicitar seu crédito',
    'credit.requirements.analysis': 'Análise SPC/Serasa',
    'credit.requirements.analysis.desc': 'Autorização para consulta do seu histórico creditício',
    'credit.requirements.address': 'Comprovação de Ponto Fixo',
    'credit.requirements.address.desc': 'Comprovante de residência ou estabelecimento comercial',
    'credit.requirements.references': 'Contatos de Referência',
    'credit.requirements.references.desc': 'Dois contatos pessoais para referência comercial',

    // Savings page
    'savings.banner.title': 'Multiplique seus Lucros com a Poupança Especial MBG',
    'savings.banner.subtitle': 'Segurança, rentabilidade e a garantia que seu dinheiro merece',
    'savings.benefits.title': 'Por que Escolher a Poupança MBG?',
    'savings.benefits.subtitle': 'Diferenciais únicos que fazem da nossa poupança a melhor opção para seu futuro',
    'savings.benefits.yield': 'Rendimento Superior',
    'savings.benefits.yield.desc': 'Rentabilidade acima da poupança tradicional com total transparência nos ganhos.',
    'savings.benefits.security': 'Segurança Garantida',
    'savings.benefits.security.desc': 'Seus investimentos protegidos com total segurança e respaldo institucional.',
    'savings.benefits.accessibility': 'Acessibilidade Total',
    'savings.benefits.accessibility.desc': 'Acesse seus recursos quando precisar com flexibilidade e praticidade.',
    'savings.growth.title': 'Veja seu Dinheiro Crescer',
    'savings.growth.subtitle': 'Simulação baseada em um investimento inicial de R$ 20.000',
    'savings.growth.initial': 'Investimento Inicial',
    'savings.growth.month12': 'Após 12 Meses',
    'savings.growth.month12.earnings': '+R$ 3.600 de rendimento',
    'savings.growth.month24': 'Após 24 Meses',
    'savings.growth.month24.earnings': '+R$ 7.848 de rendimento',
    'savings.growth.disclaimer': 'Simulação baseada em rentabilidade de 1,5% ao mês.',
    'savings.growth.warning': 'Os valores são meramente ilustrativos. Rentabilidade passada não garante resultados futuros.',
    'savings.advantages.title': 'Mais Vantagens Exclusivas',
    'savings.advantages.app': 'App Exclusivo',
    'savings.advantages.app.desc': 'Acompanhe seus rendimentos em tempo real',
    'savings.advantages.goals': 'Metas Personalizadas',
    'savings.advantages.goals.desc': 'Defina objetivos e acompanhe seu progresso',
    'savings.advantages.reports': 'Relatórios Detalhados',
    'savings.advantages.reports.desc': 'Análises completas do seu patrimônio',
    'savings.advantages.consulting': 'Consultoria Gratuita',
    'savings.advantages.consulting.desc': 'Assessoria financeira personalizada',
    'savings.cta.title': 'Abra sua Conta Poupança Hoje Mesmo',
    'savings.cta.subtitle': 'Não perca mais tempo deixando seu dinheiro parado. Comece a multiplicar seus lucros agora mesmo com a segurança que você merece.',
    'savings.cta.button': 'Fale com um Especialista',

    // Benefits page
    'benefits.banner.title': 'Um Universo de Vantagens para Clientes MBG',
    'benefits.banner.subtitle': 'Programa exclusivo de benefícios, sorteios e parcerias',
    'benefits.draws.title': 'Sorteios para Clientes Fiéis',
    'benefits.draws.subtitle': 'Todo mês realizamos sorteios especiais para nossos clientes ativos. Quanto mais você utiliza nossos serviços, maiores são suas chances de ganhar prêmios incríveis!',
    'benefits.draws.monthly': 'Prêmios Mensais',
    'benefits.draws.monthly.desc': 'Sorteios todo mês com prêmios em dinheiro, produtos e experiências únicas.',
    'benefits.draws.automatic': 'Participação Automática',
    'benefits.draws.automatic.desc': 'Clientes ativos participam automaticamente. Não precisa se inscrever!',
    'benefits.draws.multiple': 'Múltiplas Chances',
    'benefits.draws.multiple.desc': 'Quanto mais produtos MBG você usar, mais chances de ganhar você tem.',
    'benefits.draws.winners': '🏆 Últimos Ganhadores',
    'benefits.partnership.title': 'Programa de Parceria',
    'benefits.partnership.subtitle': 'Seja um parceiro MBG e ganhe comissões exclusivas indicando nossos serviços. Ideal para profissionais liberais, empreendedores e influenciadores.',
    'benefits.partnership.commission': 'Comissões Atrativas',
    'benefits.partnership.commission.desc': 'Ganhe até 5% de comissão em cada cliente indicado que contratar nossos serviços.',
    'benefits.partnership.support': 'Suporte Completo',
    'benefits.partnership.support.desc': 'Material de divulgação, treinamento e suporte especializado para seus clientes.',
    'benefits.partnership.network': 'Rede de Parceiros',
    'benefits.partnership.network.desc': 'Faça parte de uma comunidade exclusiva de parceiros de sucesso.',
    'benefits.partnership.howItWorks': 'Como Funciona',
    'benefits.partnership.step1': 'Cadastre-se',
    'benefits.partnership.step1.desc': 'Preencha nosso formulário de parceria',
    'benefits.partnership.step2': 'Receba Material',
    'benefits.partnership.step2.desc': 'Acesso a materiais e link personalizado',
    'benefits.partnership.step3': 'Indique e Ganhe',
    'benefits.partnership.step3.desc': 'Receba comissões por cada indicação convertida',
    'benefits.partnership.profile': 'Perfil Ideal para Parceiros',
    'benefits.more.title': 'Mais Benefícios Exclusivos',
    'benefits.more.subtitle': 'Ser cliente MBG vai muito além dos serviços financeiros',
    'benefits.more.education': 'Educação Financeira',
    'benefits.more.education.desc': 'Workshops e cursos gratuitos para clientes',
    'benefits.more.discounts': 'Descontos Especiais',
    'benefits.more.discounts.desc': 'Parcerias com lojas e estabelecimentos',
    'benefits.more.vip': 'Atendimento VIP',
    'benefits.more.vip.desc': 'Linha exclusiva para clientes especiais',
    'benefits.more.events': 'Eventos Exclusivos',
    'benefits.more.events.desc': 'Convites para eventos e networking',

    // Contact page
    'contact.banner.title': 'Fale Conosco',
    'contact.banner.subtitle': 'Estamos aqui para ajudar você a alcançar seus objetivos financeiros',
    'contact.form.title': 'Entre em Contato',
    'contact.form.subtitle': 'Nossa equipe de especialistas está pronta para atender você e encontrar a melhor solução financeira para suas necessidades.',
    'contact.whatsapp': 'WhatsApp',
    'contact.whatsapp.desc': 'Resposta rápida e atendimento personalizado',
    'contact.address': 'Endereço',
    'contact.instagram': 'Instagram',
    'contact.instagram.desc': 'Dicas financeiras e novidades',
    'contact.hours': 'Horário de Funcionamento',
    'contact.hours.weekdays': 'Segunda a Sexta: 8h às 18h',
    'contact.hours.saturday': 'Sábado: 8h às 12h',
    'contact.hours.sunday': 'Domingo: Fechado',
    'contact.form.message': 'Envie uma Mensagem',
    'contact.form.name': 'Nome Completo',
    'contact.form.email': 'E-mail',
    'contact.form.subject': 'Assunto',
    'contact.form.subject.select': 'Selecione um assunto',
    'contact.form.subject.credit': 'Crédito Pessoal',
    'contact.form.subject.savings': 'Poupança Especial',
    'contact.form.subject.benefits': 'Programa de Vantagens',
    'contact.form.subject.partnership': 'Programa de Parceria',
    'contact.form.subject.other': 'Outro',
    'contact.form.message.label': 'Mensagem',
    'contact.form.message.placeholder': 'Descreva como podemos ajudar você...',
    'contact.location.title': 'Nossa Localização',
    'contact.location.subtitle': 'Venha nos visitar pessoalmente em nossa sede no coração de São Paulo',

    // Specialist consultation component
    'specialist.title': 'Consultoria Financeira Personalizada',
    'specialist.subtitle': 'Nossos especialistas analisam seu perfil e oferecem as melhores condições do mercado. Atendimento exclusivo e soluções sob medida para você.',
    'specialist.analysis': 'Análise Personalizada',
    'specialist.analysis.desc': 'Nossos especialistas analisam seu perfil financeiro para oferecer as melhores condições.',
    'specialist.conditions': 'Condições Personalizadas',
    'specialist.conditions.desc': 'Acesso a condições exclusivas e vantagens especiais para nossos clientes.',
    'specialist.exclusive': 'Atendimento Exclusivo',
    'specialist.exclusive.desc': 'Suporte dedicado durante todo o processo, do início ao final.',
    'specialist.response': 'Resposta Rápida',
    'specialist.response.desc': 'Análise e resposta em até 24 horas úteis.',
    'specialist.expertise': 'Expertise Comprovada',
    'specialist.expertise.desc': 'Mais de 10 anos de experiência no mercado financeiro.',
    'specialist.process': 'Processo Simplificado',
    'specialist.process.desc': 'Menos burocracia, mais agilidade para você.',
    'specialist.cta.title': 'Fale com um Especialista',
    'specialist.cta.subtitle': 'Agende sua consultoria gratuita e descubra as melhores opções para seu perfil financeiro.',
    'specialist.cta.free': 'Consultoria 100% gratuita',
    'specialist.cta.analysis': 'Análise completa do seu perfil',
    'specialist.cta.proposal': 'Proposta personalizada',
    'specialist.cta.exclusive': 'Condições exclusivas',
    'specialist.cta.button': 'Falar com Especialista',
    'specialist.cta.response': 'Resposta em até 24h úteis • Atendimento de segunda a sexta',

    // Footer
    'footer.description': 'Soluções financeiras descomplicadas para transformar seus planos em realidade. Crédito simples e poupança segura com total transparência.',
    'footer.developed': 'Desenvolvido com 💛 para transformar vidas através de soluções financeiras inteligentes.',
    
    // WhatsApp Messages
    'whatsapp.default': 'Olá! Gostaria de saber mais sobre os serviços da MBG Financeira.',
    'whatsapp.credit': 'Olá! Tenho interesse no Crédito Pessoal da MBG Financeira.',
    'whatsapp.savings': 'Olá! Gostaria de saber mais sobre a Poupança Especial.',
    'whatsapp.contact': 'Olá! Vim através do site e gostaria de falar com um especialista.',
    'whatsapp.consultation': 'Olá! Gostaria de agendar uma consultoria financeira personalizada com um especialista da MBG. Podem me ajudar com as melhores condições para meu perfil?',
  },
  es: {
    // Header
    'nav.home': 'Inicio',
    'nav.about': 'Acerca de',
    'nav.services': 'Servicios',
    'nav.benefits': 'Ventajas',
    'nav.blog': 'Blog',
    'nav.contact': 'Contacto',
    'nav.contactUs': 'Contáctanos',
    'nav.personalCredit': 'Crédito Personal',
    'nav.specialSavings': 'Ahorros Especiales',
    
    // Common
    'common.learnMore': 'Saber Más',
    'common.getStarted': 'Comenzar Ahora',
    'common.contactSpecialist': 'Hablar con Especialista',
    'common.simulateNow': 'Simular Ahora',
    'common.sendMessage': 'Enviar Mensaje',
    'common.sending': 'Enviando...',
    'common.allRightsReserved': 'Todos los derechos reservados',
    'common.quickLinks': 'Enlaces Rápidos',
    'common.contact': 'Contacto',
    
    // Home page
    'home.hero.welcome': 'BIENVENIDO(A) A',
    'home.hero.company': 'MBG FINANCIERA',
    'home.hero.subtitle': 'Crédito Simple y Ahorros Seguros.',
    'home.hero.description': 'Soluciones financieras sin burocracia para transformar tus planes en realidad.',
    'home.hero.cta': 'Simula tu Crédito Ahora',
    'home.services.title': 'Soluciones Financieras a tu Alcance',
    'home.services.subtitle': 'Ofrecemos productos financieros pensados para facilitar tu vida y realizar tus sueños.',
    'home.services.credit.title': 'Crédito Facilitado',
    'home.services.credit.description': 'Accede al crédito que necesitas con pagos semanales flexibles y condiciones justas. Proceso rápido y sin complicaciones.',
    'home.services.savings.title': 'Ahorros Especiales',
    'home.services.savings.description': 'Multiplica tus ganancias. Haz que tu dinero rinda con total seguridad y garantía. Rentabilidad superior al ahorro tradicional.',
    'home.features.title': 'Ventajas que solo MBG Ofrece',
    'home.features.subtitle': 'Descubre por qué somos la opción correcta para tus necesidades financieras.',
    'home.testimonials.title': 'La Confianza de Nuestros Clientes',
    'home.testimonials.subtitle': 'Ve lo que nuestros clientes dicen sobre nuestros servicios y resultados.',
    'home.cta.title': '¿Listo para empezar?',
    'home.cta.subtitle': 'Habla con uno de nuestros especialistas y descubre la mejor solución para ti. Estamos aquí para transformar tus planes en realidad.',
    'home.cta.button': 'Contáctanos por WhatsApp',

    // About page
    'about.banner.title': 'Nuestra Historia, Tu Futuro Financiero',
    'about.banner.subtitle': 'Conoce MBG Financiera y nuestra misión de transformar vidas a través de soluciones financieras accesibles',
    'about.mission.title': 'MBG: Nacimos para Simplificar',
    'about.mission.description': 'MBG Financiera nació con el propósito de democratizar el acceso a los servicios financieros en Brasil. Creemos que todos merecen oportunidades justas y transparentes para realizar sus sueños y superar desafíos financieros. Nuestra misión es ofrecer crédito accesible y ahorros seguros, siempre con la confianza y el respeto que nuestros clientes merecen.',
    'about.values.trust': 'Confianza',
    'about.values.trust.desc': 'Transparencia total en todas nuestras operaciones y relaciones con clientes.',
    'about.values.accessibility': 'Accesibilidad',
    'about.values.accessibility.desc': 'Soluciones financieras pensadas para atender todos los perfiles de brasileños.',
    'about.values.simplicity': 'Simplicidad',
    'about.values.simplicity.desc': 'Procesos simplificados y atención humanizada para facilitar tu vida.',
    'about.values.commitment': 'Compromiso',
    'about.values.commitment.desc': 'Dedicación genuina en ayudar a nuestros clientes a alcanzar sus objetivos.',
    'about.location.title': 'Nuestra Casa es tu Casa',
    'about.location.subtitle': 'Visítanos en nuestra sede y conoce personalmente a nuestro equipo de especialistas financieros.',
    'about.location.address': 'Dirección',
    'about.location.hours': 'Horario de Funcionamiento:',
    'about.location.weekdays': 'Lunes a Viernes: 8h a 18h',
    'about.location.saturday': 'Sábado: 8h a 12h',

    // Credit Personal page
    'credit.banner.title': 'Crédito Personal Rápido y sin Burocracia',
    'credit.banner.subtitle': 'El impulso que necesitas, con las condiciones que mereces',
    'credit.howItWorks.title': 'Cómo Funciona',
    'credit.howItWorks.subtitle': 'Proceso simple y transparente en solo 3 etapas',
    'credit.howItWorks.step1': '1. Simulación Online',
    'credit.howItWorks.step1.desc': 'Haz tu simulación rápidamente y descubre las mejores condiciones para tu perfil.',
    'credit.howItWorks.step2': '2. Análisis Rápido',
    'credit.howItWorks.step2.desc': 'Nuestro equipo analiza tu perfil en hasta 24 horas hábiles con total seguridad.',
    'credit.howItWorks.step3': '3. Dinero en la Cuenta',
    'credit.howItWorks.step3.desc': '¿Aprobado? El valor se deposita directamente en tu cuenta de forma rápida y segura.',
    'credit.conditions.title': 'Nuestras Condiciones',
    'credit.conditions.subtitle': 'Transparencia total y condiciones justas para ti',
    'credit.conditions.fair': 'Condiciones Justas',
    'credit.conditions.fair.desc': 'Valores Transparentes',
    'credit.conditions.flexible': 'Pago Flexible',
    'credit.conditions.flexible.desc': 'Pagos Semanales',
    'credit.conditions.amounts': 'Valores',
    'credit.conditions.amounts.range': 'R$ 1.000 hasta R$ 5.000',
    'credit.requirements.title': 'Prerrequisitos',
    'credit.requirements.subtitle': 'Documentación necesaria para solicitar tu crédito',
    'credit.requirements.analysis': 'Análisis SPC/Serasa',
    'credit.requirements.analysis.desc': 'Autorización para consulta de tu historial crediticio',
    'credit.requirements.address': 'Comprobación de Punto Fijo',
    'credit.requirements.address.desc': 'Comprobante de residencia o establecimiento comercial',
    'credit.requirements.references': 'Contactos de Referencia',
    'credit.requirements.references.desc': 'Dos contactos personales para referencia comercial',

    // Savings page
    'savings.banner.title': 'Multiplica tus Ganancias con los Ahorros Especiales MBG',
    'savings.banner.subtitle': 'Seguridad, rentabilidad y la garantía que tu dinero merece',
    'savings.benefits.title': '¿Por qué Elegir los Ahorros MBG?',
    'savings.benefits.subtitle': 'Diferenciales únicos que hacen de nuestros ahorros la mejor opción para tu futuro',
    'savings.benefits.yield': 'Rendimiento Superior',
    'savings.benefits.yield.desc': 'Rentabilidad superior al ahorro tradicional con total transparencia en las ganancias.',
    'savings.benefits.security': 'Seguridad Garantizada',
    'savings.benefits.security.desc': 'Tus inversiones protegidas con total seguridad y respaldo institucional.',
    'savings.benefits.accessibility': 'Accesibilidad Total',
    'savings.benefits.accessibility.desc': 'Accede a tus recursos cuando lo necesites con flexibilidad y practicidad.',
    'savings.growth.title': 'Ve tu Dinero Crecer',
    'savings.growth.subtitle': 'Simulación basada en una inversión inicial de R$ 20.000',
    'savings.growth.initial': 'Inversión Inicial',
    'savings.growth.month12': 'Después de 12 Meses',
    'savings.growth.month12.earnings': '+R$ 3.600 de rendimiento',
    'savings.growth.month24': 'Después de 24 Meses',
    'savings.growth.month24.earnings': '+R$ 7.848 de rendimiento',
    'savings.growth.disclaimer': 'Simulación basada en rentabilidad del 1,5% mensual.',
    'savings.growth.warning': 'Los valores son meramente ilustrativos. Rentabilidad pasada no garantiza resultados futuros.',
    'savings.advantages.title': 'Más Ventajas Exclusivas',
    'savings.advantages.app': 'App Exclusivo',
    'savings.advantages.app.desc': 'Acompaña tus rendimientos en tiempo real',
    'savings.advantages.goals': 'Metas Personalizadas',
    'savings.advantages.goals.desc': 'Define objetivos y acompaña tu progreso',
    'savings.advantages.reports': 'Informes Detallados',
    'savings.advantages.reports.desc': 'Análisis completos de tu patrimonio',
    'savings.advantages.consulting': 'Consultoría Gratuita',
    'savings.advantages.consulting.desc': 'Asesoría financiera personalizada',
    'savings.cta.title': 'Abre tu Cuenta de Ahorros Hoy Mismo',
    'savings.cta.subtitle': 'No pierdas más tiempo dejando tu dinero parado. Empieza a multiplicar tus ganancias ahora mismo con la seguridad que mereces.',
    'savings.cta.button': 'Habla con un Especialista',

    // Benefits page
    'benefits.banner.title': 'Un Universo de Ventajas para Clientes MBG',
    'benefits.banner.subtitle': 'Programa exclusivo de beneficios, sorteos y alianzas',
    'benefits.draws.title': 'Sorteos para Clientes Fieles',
    'benefits.draws.subtitle': 'Cada mes realizamos sorteos especiales para nuestros clientes activos. ¡Cuanto más uses nuestros servicios, mayores serán tus oportunidades de ganar premios increíbles!',
    'benefits.draws.monthly': 'Premios Mensuales',
    'benefits.draws.monthly.desc': 'Sorteos cada mes con premios en dinero, productos y experiencias únicas.',
    'benefits.draws.automatic': 'Participación Automática',
    'benefits.draws.automatic.desc': '¡Los clientes activos participan automáticamente. No necesitas inscribirte!',
    'benefits.draws.multiple': 'Múltiples Oportunidades',
    'benefits.draws.multiple.desc': 'Cuantos más productos MBG uses, más oportunidades de ganar tienes.',
    'benefits.draws.winners': '🏆 Últimos Ganadores',
    'benefits.partnership.title': 'Programa de Alianza',
    'benefits.partnership.subtitle': 'Sé un aliado MBG y gana comisiones exclusivas recomendando nuestros servicios. Ideal para profesionales independientes, emprendedores e influenciadores.',
    'benefits.partnership.commission': 'Comisiones Atractivas',
    'benefits.partnership.commission.desc': 'Gana hasta 5% de comisión en cada cliente recomendado que contrate nuestros servicios.',
    'benefits.partnership.support': 'Soporte Completo',
    'benefits.partnership.support.desc': 'Material de divulgación, entrenamiento y soporte especializado para tus clientes.',
    'benefits.partnership.network': 'Red de Aliados',
    'benefits.partnership.network.desc': 'Forma parte de una comunidad exclusiva de aliados exitosos.',
    'benefits.partnership.howItWorks': 'Cómo Funciona',
    'benefits.partnership.step1': 'Regístrate',
    'benefits.partnership.step1.desc': 'Completa nuestro formulario de alianza',
    'benefits.partnership.step2': 'Recibe Material',
    'benefits.partnership.step2.desc': 'Acceso a materiales y enlace personalizado',
    'benefits.partnership.step3': 'Recomienda y Gana',
    'benefits.partnership.step3.desc': 'Recibe comisiones por cada recomendación convertida',
    'benefits.partnership.profile': 'Perfil Ideal para Aliados',
    'benefits.more.title': 'Más Beneficios Exclusivos',
    'benefits.more.subtitle': 'Ser cliente MBG va mucho más allá de los servicios financieros',
    'benefits.more.education': 'Educación Financiera',
    'benefits.more.education.desc': 'Talleres y cursos gratuitos para clientes',
    'benefits.more.discounts': 'Descuentos Especiales',
    'benefits.more.discounts.desc': 'Alianzas con tiendas y establecimientos',
    'benefits.more.vip': 'Atención VIP',
    'benefits.more.vip.desc': 'Línea exclusiva para clientes especiales',
    'benefits.more.events': 'Eventos Exclusivos',
    'benefits.more.events.desc': 'Invitaciones a eventos y networking',

    // Contact page
    'contact.banner.title': 'Contáctanos',
    'contact.banner.subtitle': 'Estamos aquí para ayudarte a alcanzar tus objetivos financieros',
    'contact.form.title': 'Ponte en Contacto',
    'contact.form.subtitle': 'Nuestro equipo de especialistas está listo para atenderte y encontrar la mejor solución financiera para tus necesidades.',
    'contact.whatsapp': 'WhatsApp',
    'contact.whatsapp.desc': 'Respuesta rápida y atención personalizada',
    'contact.address': 'Dirección',
    'contact.instagram': 'Instagram',
    'contact.instagram.desc': 'Consejos financieros y novedades',
    'contact.hours': 'Horario de Funcionamiento',
    'contact.hours.weekdays': 'Lunes a Viernes: 8h a 18h',
    'contact.hours.saturday': 'Sábado: 8h a 12h',
    'contact.hours.sunday': 'Domingo: Cerrado',
    'contact.form.message': 'Envía un Mensaje',
    'contact.form.name': 'Nombre Completo',
    'contact.form.email': 'E-mail',
    'contact.form.subject': 'Asunto',
    'contact.form.subject.select': 'Selecciona un asunto',
    'contact.form.subject.credit': 'Crédito Personal',
    'contact.form.subject.savings': 'Ahorros Especiales',
    'contact.form.subject.benefits': 'Programa de Ventajas',
    'contact.form.subject.partnership': 'Programa de Alianza',
    'contact.form.subject.other': 'Otro',
    'contact.form.message.label': 'Mensaje',
    'contact.form.message.placeholder': 'Describe cómo podemos ayudarte...',
    'contact.location.title': 'Nuestra Ubicación',
    'contact.location.subtitle': 'Ven a visitarnos personalmente en nuestra sede en el corazón de São Paulo',

    // Specialist consultation component
    'specialist.title': 'Consultoría Financiera Personalizada',
    'specialist.subtitle': 'Nuestros especialistas analizan tu perfil y ofrecen las mejores condiciones del mercado. Atención exclusiva y soluciones a tu medida.',
    'specialist.analysis': 'Análisis Personalizado',
    'specialist.analysis.desc': 'Nuestros especialistas analizan tu perfil financiero para ofrecer las mejores condiciones.',
    'specialist.conditions': 'Condiciones Personalizadas',
    'specialist.conditions.desc': 'Acceso a condiciones exclusivas y ventajas especiales para nuestros clientes.',
    'specialist.exclusive': 'Atención Exclusiva',
    'specialist.exclusive.desc': 'Soporte dedicado durante todo el proceso, de principio a fin.',
    'specialist.response': 'Respuesta Rápida',
    'specialist.response.desc': 'Análisis y respuesta en hasta 24 horas hábiles.',
    'specialist.expertise': 'Experiencia Comprobada',
    'specialist.expertise.desc': 'Más de 10 años de experiencia en el mercado financiero.',
    'specialist.process': 'Proceso Simplificado',
    'specialist.process.desc': 'Menos burocracia, más agilidad para ti.',
    'specialist.cta.title': 'Habla con un Especialista',
    'specialist.cta.subtitle': 'Agenda tu consultoría gratuita y descubre las mejores opciones para tu perfil financiero.',
    'specialist.cta.free': 'Consultoría 100% gratuita',
    'specialist.cta.analysis': 'Análisis completo de tu perfil',
    'specialist.cta.proposal': 'Propuesta personalizada',
    'specialist.cta.exclusive': 'Condiciones exclusivas',
    'specialist.cta.button': 'Hablar con Especialista',
    'specialist.cta.response': 'Respuesta en hasta 24h hábiles • Atención de lunes a viernes',

    // Footer
    'footer.description': 'Soluciones financieras simplificadas para transformar tus planes en realidad. Crédito simple y ahorros seguros con total transparencia.',
    'footer.developed': 'Desarrollado con 💛 para transformar vidas a través de soluciones financieras inteligentes.',
    
    // WhatsApp Messages
    'whatsapp.default': '¡Hola! Me gustaría saber más sobre los servicios de MBG Financiera.',
    'whatsapp.credit': '¡Hola! Tengo interés en el Crédito Personal de MBG Financiera.',
    'whatsapp.savings': '¡Hola! Me gustaría saber más sobre los Ahorros Especiales.',
    'whatsapp.contact': '¡Hola! Vengo del sitio web y me gustaría hablar con un especialista.',
    'whatsapp.consultation': '¡Hola! Me gustaría agendar una consultoría financiera personalizada con un especialista de MBG. ¿Pueden ayudarme con las mejores condiciones para mi perfil?',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('mbg-language');
    return (saved as Language) || 'pt';
  });

  useEffect(() => {
    localStorage.setItem('mbg-language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.pt] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};